---
configure_dotfiles: false
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Notes
  - Reminders
  - Photos
  - Messages
  - FaceTime
  - Contacts
  - Calendar
  - Maps
  - News
  - iTunes

dockitems_persist:
  - name: "Zed"
    path: "/Applications/Zed.app/"
    pos: 1
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 2
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 3
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 4
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 5
  - name: "Obsidian"
    path: "/Applications/Obsidian.app/"
    pos: 6
  - name: "Warp"
    path: "/Applications/Warp.app/"
    pos: 7

configure_sudoers: true
sudoers_custom_config: |
   # Allow users in admin group to use sudo with no password.
   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  - smudge/smudge/nightlight
  - baobab
  - mas
  - ansible
  - automake
  - bash-completion
  - borgmatic
  - cmake
  - mqttx-cli
  - espeak
  - esptool
  - ffmpeg
  - exiftool
  - direnv
  - gifsicle
  - gcc@13
  - git
  - git-lfs
  - imagemagick
  - jq
  - libmagic
  - pyenv-virtualenv
  - sqlite
  - rust
  - pngpaste
  - readline
  - openssl
  - pv
  - wget
  - watch
  - youtube-dl
  - htop
  - zlib
  - zola

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - slack
  - visual-studio-code
  - iterm2
  - obsidian
  - zed
  - intellij-idea-ce
  - arduino-ide
  - balenaetcher
  - bambu-studio
  - displaylink
  - gimp
  - inkscape
  - kicad
  - mqttx
  - syncthing
  - tailscale
  - vlc
  - zoom
  - warp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_upgrade_all_apps: false
mas_signin_dialog: false
mas_installed_apps: []

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []

# Set to 'true' to configure Sublime Text.
configure_sublime: false

configure_sdkman: true

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: [ ]
