---
- name: Run nightlight schedule.
  command: "nightlight schedule 7:00pm 6am"
  changed_when: false
- name: Pyenv install.
  command: "pyenv install 3.13.1"
  environment:
    CONFIGURE_OPTS: "--enable-optimizations"
  register: pyenv_result
  changed_when: false
  failed_when: pyenv_result.rc != 0 and "already exists" not in pyenv_result.stderr

# - name: Run .osx dotfiles.
#   command: "{{ osx_script }}"
#   changed_when: false
